# Choose whatever you want, version >= 1.16
FROM golang:1.23-bookworm

WORKDIR /app
RUN apt-get update && apt-get install -y fish

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod tidy

CMD ["air", "-c", ".air.toml"]